[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.8.0"
edition = "2024"
# authors = ["Koosha H <git@koosha.io>"]
homepage = "https://koosha.io/project/typekin"
repository = "https://gitlab.com/hkoosha/typekin"
# license = "MIT"
keywords = ["newtype", "derive", "invariant", "no_std"]
categories = ["data-structures"]
rust-version = "1.97"

[workspace.lints.clippy]
needless_return = "allow"

[workspace.dependencies]
syn = { version = "3", features = ["full", "visit-mut"] }
quote = { version = "1", }
proc-macro2 = { version = "1", features = ["span-locations"] }
