[package]
name = "typekin_testing"
authors = ["Koosha H <git@koosha.io>"]
license = "GPL-3.0-only"
description = "test helpers for typekin crate"

edition.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

version = "0.0.0"
publish = false

[lints]
workspace = true
