[package]
name = "typekin_testing"
authors = ["Koosha H <git@koosha.io>"]
version = "0.0.0"
edition = "2024"
license = "AGPL-3.0-only"
homepage = "https://koosha.io/project/typekin"
repository = "https://gitlab.com/hkoosha/typekin"
description = "Unpublished crate only for testing the crate: typekin"

publish = false

[lints.clippy]
needless_return = "allow"

[lints.cargo]
unused_dependencies = "allow"

[dependencies]
typekin = { path = ".." }

[[bin]]
name = "my_u32"
path = "src/my_u32.rs"
test = false
bench = false

[[bin]]
name = "my_u32_const"
path = "src/my_u32_const.rs"
test = false
bench = false
