[package]
name = "typekin"
authors = ["Koosha H <git@koosha.io>"]
license = "GPL-3.0-only"
description = "new-type pattern with concept of Friends borrowed from c++"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[[bin]]
name = "typekin-unexpand"
path = "src/main.rs"

[lib]
proc-macro = true

[dependencies]
#syn = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }

bitflags = "2.13.1"

[dev-dependencies]
typekin_testing = { path = "../typekin_testing" }

[[example]]
name = "my_u32"
path = "examples/my_u32.rs"

[[example]]
name = "my_u32_exp"
path = "examples/my_u32_exp.rs"

[[example]]
name = "my_u32_non_const"
path = "examples/my_u32_non_const.rs"

[[example]]
name = "my_u32_non_const_exp"
path = "examples/my_u32_non_const_exp.rs"

[[example]]
name = "my_thingy"
path = "examples/my_thingy.rs"
[[example]]
name = "thingy_exp"
path = "examples/my_thingy_exp.rs"

[[example]]
name = "my_flag"
path = "examples/my_flag.rs"
[[example]]
name = "flag_exp"
path = "examples/my_flag_exp.rs"
