[package]
name = "typekin"
authors = ["Koosha H <git@koosha.io>"]
license = "MIT"
description = "new-type pattern with concept of Friends borrowed from c++, no-std and fully const"

version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "typekin-unexpand"
path = "src/main.rs"

[lib]
proc-macro = true

[features]
default = []
better-bin = ["syn/extra-traits"]

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
typekin_testing = { path = "../typekin_testing" }

[[example]]
name = "my_u32"
path = "examples/my_u32.rs"
[[example]]
name = "my_u32_exp"
path = "examples/my_u32_exp.rs"

[[example]]
name = "my_u32_non_const"
path = "examples/my_u32_non_const.rs"
[[example]]
name = "my_u32_non_const_exp"
path = "examples/my_u32_non_const_exp.rs"

[[example]]
name = "my_flag"
path = "examples/my_flag.rs"
[[example]]
name = "flag_exp"
path = "examples/my_flag_exp.rs"

[[example]]
name = "my_i128"
path = "examples/my_i128.rs"
[[example]]
name = "my_i128_exp"
path = "examples/my_i128_exp.rs"
